---
title: "Historical dplyr benchmark results"
author: "Kirill Müller"
output:
  rmarkdown::html_document
---

```{r}
r <- rprojroot::is_r_package$make_fix_file()

library(dplyr)
library(ggplot2)
```

```{r}
log <- system2("git", c("log --format='%H %aI' --first-parent master --", r("src"), r("inst/include")), stdout = TRUE)

log_df <-
  log %>%
  rev %>%
  strsplit(" ", fixed = TRUE) %>%
  purrr::transpose() %>%
  `names<-`(c("sha", "commit_time")) %>% 
  lapply(unlist) %>% 
  as_data_frame %>% 
  mutate(commit_time = as.POSIXct(commit_time)) %>% 
  mutate(commit_id = seq_along(commit_time))
```

```{r}
csv_files <- dir(r("inst/benchmark"), full.names = TRUE, pattern = glob2rx("*.csv"))
names(csv_files) <- gsub("^.*[^0-9a-f]([0-9a-f]+)[.]csv$", "\\1",
                         as.character(csv_files))
csv_data <- lapply(csv_files, read.csv, row.names = NULL, stringsAsFactors = FALSE)
full_data <- bind_rows(csv_data, .id = "sha")
```

```{r}
plot_data <- log_df %>%
  inner_join(full_data, by = "sha") %>%
  filter(grepl("dplyr_df", name))
```


```{r}
plot_data %>%
  ggplot(aes(x = commit_time, y = median_time / 1e9, color = name, group = name)) +
  geom_line() +
  geom_point()
```



```{r}
plot_data %>%
  filter(grepl("filter|mutate", name)) %>% 
  ggplot(aes(x = commit_id, y = median_time / 1e9, color = name, group=name)) +
  geom_line() +
  geom_point()
```

